version: "3.9"
services:
  db:
    build:
      context: data/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
      
  ui:
    build:
      context: ui
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ui/public/www/html/health:/var/www/html/health:ro
    environment:
      - NGINX_HOST=health.com
      - NGINX_PORT=80
    secrets:
      - source: site.crt
        target: site.crt
      - source: site.key
        target: site.key
secrets:
  site.crt:
    file: ./ui/nginx/nginx-selfsigned.crt
  site.key:
    file: ./ui/nginx/nginx-selfsigned.key